#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/workspace ~/.dotfiles -mindepth 0 -maxdepth 1 -type d | fzf)
fi


if [[ -z $selected ]]; then
    exit 0
fi

session_name=$(basename $selected | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]] ; then
    tmux new-session -c $selected -s $session_name
    exit 0
fi

if ! tmux has-session -t $session_name 2>/dev/null; then
    tmux new-session -c $selected -ds $session_name
fi

if [[ -z $TMUX ]]; then
    tmux attach-session -t $session_name
else
    tmux switch-client -t $session_name
fi
